apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: consumer-service:latest   
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "kafka1:9092"         
            - name: KAFKA_TOPIC
              value: "dados-sensores"
            - name: KAFKA_CONSUMER_GROUP
              value: "consumer-service"

---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  type: NodePort
  selector:
    app: consumer-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081   
